#!/usr/bin/env python3
"""Build the ColdFire unit `playmodes.s` from playmode.c + adapter.c + hooks.s,
or --check that the checked-in copy is current, or --dry to compile only. Mirrors EUCLID's
generate_control.py: the algorithm stays in C, the builder links GNU-as.

Needs m68k-elf-gcc (the same compiler the rest of the native build uses).
No firmware is read.
"""
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FLAGS = ['-mcpu=5475', '-msoft-float', '-O2', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-tree-loop-distribute-patterns', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer',
         '-fno-tree-loop-distribute-patterns', '-std=c11', '-Wall', '-Wextra',
         '-Werror']
SOURCES = ('playmode.c', 'adapter.c')
# Stock targets the unit may reach besides its own labels: the toast, and
# the places the detour stubs jump back to or call (manifest.py, hooks.s).
# Anything else (a libgcc helper such as __udivdi3, a memset the optimiser
# invented, a mistyped return address) fails the build.
STOCK_CALLS = {'NOTIFY', 'REBUILD', '0x4009b2be', '0x40040256', '0x400491a6', '0x4009dc8c', '0x4009e3e2',
               '0x400a2d74', '0x400a39be', '0x4009c3e0', '0x400a2216', '0x400a24dc', '0x400a27ee',
               'WRITE', '0x400866da', '0x400867b0', '0x40088224', '0x400888b8'}


def compiler():
    gcc = shutil.which('m68k-elf-gcc')
    if not gcc:
        sys.exit('m68k-elf-gcc not found (brew install m68k-elf-gcc, or the SDK toolchain)')
    return gcc


def generate():
    gcc = compiler()
    parts = ['| Generated by generate.py from playmode.c, adapter.c and hooks.s.\n'
             '| Edit those; run `python3 generate.py` to refresh this file.\n']
    # One translation unit: compiled apart, each file numbers GCC's local
    # labels (.L3, .L4 ...) from the start and the concatenation collides.
    with tempfile.TemporaryDirectory() as td:
        unit = pathlib.Path(td) / 'playmodes_unit.c'
        unit.write_text(''.join(f'#include "{HERE / name}"\n' for name in SOURCES))
        out = pathlib.Path(td) / 'unit.s'
        # Relative name in the temp dir, so `.file` is the same on every run.
        subprocess.run([gcc, *FLAGS, '-I', str(HERE), '-S', unit.name, '-o', str(out)],
                       cwd=td, check=True)
        parts.append('| ---- playmode.c + adapter.c ----\n' + out.read_text())
    parts.append('| ---- hooks.s ----\n' + (HERE / 'hooks.s').read_text())
    return '\n'.join(parts)


def external_calls(source):
    calls = set()
    for line in source.splitlines():
        words = line.split()
        if len(words) >= 2 and words[0] in ('jsr', 'jbsr', 'bsr', 'jmp', 'jra', 'bsr.l'):
            target = words[1].split(',')[0].lstrip('(').rstrip(')')
            if not target.startswith(('.', '%')):
                calls.add(target)
    # GCC's own local labels can carry dots (pm_map.part.0, .L5).
    defined = {m.group(1) for m in re.finditer(r'^([A-Za-z_.$][\w.$]*):', source, re.M)}
    return calls - defined - STOCK_CALLS


def assemble(source):
    """Assemble the whole unit for the 5475, so a stub the ColdFire cannot
    encode fails here and not in the firmware build."""
    with tempfile.TemporaryDirectory() as td:
        src = pathlib.Path(td) / 'playmodes.s'
        src.write_text(source)
        result = subprocess.run([compiler(), '-mcpu=5475', '-c', '-x', 'assembler', str(src),
                                 '-o', str(pathlib.Path(td) / 'playmodes.o')],
                                capture_output=True, text=True)
        if result.returncode:
            sys.exit('playmodes.s does not assemble for the 5475:\n' + result.stderr)


if __name__ == '__main__':
    source = generate()
    stray = external_calls(source)
    if stray:
        sys.exit(f'playmodes.s calls outside the unit: {sorted(stray)}')
    assemble(source)
    dest = HERE / 'playmodes.s'
    if '--dry' in sys.argv:
        print(f'ColdFire compile and assembly OK ({len(source.splitlines())} lines), no calls outside the unit')
    elif '--check' in sys.argv:
        if not dest.exists() or dest.read_text() != source:
            sys.exit('playmodes.s is stale: run python3 generate.py')
        print('playmodes.s matches playmode.c, adapter.c and hooks.s')
    else:
        dest.write_text(source)
        print(f'wrote {dest.name} ({len(source.splitlines())} lines): assembles for the 5475, no library calls')
