| Generated by generate.py from playmode.c, adapter.c and hooks.s.
| Edit those; run `python3 generate.py` to refresh this file.

| ---- playmode.c + adapter.c ----
#NO_APP
	.file	"playmodes_unit.c"
	.text
	.align	2
	.type	pm_map.part.0, @function
pm_map.part.0:
	lea (-32,%sp),%sp
	move.l 40(%sp),%a1
	move.l %a1,%a0
	movem.l #252,(%sp)
	move.l 36(%sp),%d0
	moveq #64,%d2
	move.l 48(%sp),%d1
	cmp.l %a1,%d2
	jcc .L2
	move.w #64,%a0
.L2:
	cmp.l %a0,%d1
	jcs .L3
	move.l %a0,%d3
	remu.l %d3,%d2:%d1
	divu.l %d3,%d1
	add.l %d1,44(%sp)
	move.l %d2,%d1
.L3:
	mov3q.l #3,%d4
	cmp.l %d0,%d4
	jeq .L4
	jcs .L5
	mov3q.l #1,%d6
	cmp.l %d0,%d6
	jeq .L6
	subq.l #2,%d0
	tst.l %d0
	jne .L10
	mov3q.l #1,%d3
	cmp.l %a1,%d3
	jeq .L17
	move.l %a0,%d2
	subq.l #1,%d2
	mvz.w %d2,%d2
	move.l 44(%sp),%d3
	move.w %a0,%d4
	add.l %d2,%d2
	remu.l %d2,%d0:%d3
	mulu.w %d4,%d0
	add.l %d0,%d1
	remu.l %d2,%d0:%d1
	cmp.l %a0,%d0
	jcs .L1
	sub.l %d0,%d2
	move.l %d2,%d0
.L1:
	movem.l (%sp),#252
	lea (32,%sp),%sp
	rts
.L5:
	subq.l #4,%d0
	tst.l %d0
	jne .L10
	mov3q.l #1,%d0
	cmp.l %a1,%d0
	jcc .L17
	sub.l %a1,%a1
.L13:
	addq.l #1,%a1
	move.l %d0,%d3
	move.l %a1,%d2
	lsl.l %d2,%d3
	cmp.l %a0,%d3
	jcs .L13
	tst.l %a1
	jeq .L17
	move.l 44(%sp),%d2
	move.l #668265263,%d4
	move.l %d1,%d0
	move.l #2146121005,%d7
	move.l 52(%sp),%d1
	move.l %a1,%d6
	muls.l %d4,%d2
	moveq #15,%d4
	lsr.l #1,%d6
	subq.l #1,%d3
	move.l %d6,28(%sp)
	move.l #-2073254261,%d6
	eor.l %d2,%d1
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	eor.l %d2,%d1
	muls.l %d7,%d1
	mov3q.l #1,%d7
	move.l %d1,%d2
	lsr.l %d4,%d2
	eor.l %d2,%d1
	muls.l %d6,%d1
	move.l %d1,%d2
	clr.w %d2
	swap %d2
	eor.l %d2,%d1
	move.l %d1,%d5
	add.l #-626627285,%d5
	move.l %d1,24(%sp)
	cmp.l %a1,%d7
	jeq .L18
.L25:
	move.l 28(%sp),%d4
	move.l 24(%sp),%d2
.L15:
	move.l %d2,%d1
	move.l #2146121005,%d6
	clr.w %d1
	swap %d1
	moveq #15,%d7
	eor.l %d2,%d1
	add.l #-1640531527,%d2
	muls.l %d6,%d1
	move.l %d1,%d6
	lsr.l %d7,%d6
	mov3q.l #1,%d7
	eor.l %d6,%d1
	move.l #-2073254261,%d6
	muls.l %d6,%d1
	move.l %d1,%d6
	clr.w %d6
	swap %d6
	eor.l %d6,%d1
	move.l %d1,%d6
	lsr.l #8,%d1
	add.l %d6,%d6
	or.l %d7,%d6
	muls.l %d0,%d6
	add.l %d6,%d1
	and.l %d3,%d1
	move.l %d1,%d0
	lsr.l %d4,%d0
	eor.l %d1,%d0
	cmp.l %d5,%d2
	jne .L15
	and.l %d3,%d0
	cmp.l %a0,%d0
	jcs .L1
	mov3q.l #1,%d7
	cmp.l %a1,%d7
	jne .L25
.L18:
	move.l 24(%sp),%d2
	mov3q.l #1,%d4
	jra .L15
.L10:
	movem.l (%sp),#252
	move.l %d1,%d0
	lea (32,%sp),%sp
	rts
.L4:
	move.l 44(%sp),%d0
	move.l #-2048144789,%d6
	move.l #-1028477387,%d7
	moveq #15,%d2
	muls.l %d7,%d1
	muls.l %d6,%d0
	move.l #-2073254261,%d3
	move.l 52(%sp),%d4
	move.l #2146121005,%d6
	move.w %a0,%d7
	move.l %d0,%a1
	lea 1(%a1,%d1.l),%a1
	move.l %a1,%d0
	move.l %a1,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	muls.l %d3,%d0
	move.l %d0,%d1
	eor.l %d4,%d0
	clr.w %d1
	swap %d1
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d6,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	muls.l %d3,%d0
	clr.w %d0
	swap %d0
	mulu.w %d7,%d0
	movem.l (%sp),#252
	clr.w %d0
	swap %d0
	lea (32,%sp),%sp
	rts
.L6:
	movem.l (%sp),#252
	move.l %a0,%d0
	subq.l #1,%d0
	sub.l %d1,%d0
	lea (32,%sp),%sp
	rts
.L17:
	movem.l (%sp),#252
	clr.l %d0
	lea (32,%sp),%sp
	rts
	.size	pm_map.part.0, .-pm_map.part.0
	.align	2
	.type	run_seed.isra.0, @function
run_seed.isra.0:
	move.l %d2,-(%sp)
	move.l #-2048144789,%d0
	move.l 16(%sp),%d1
	move.l #-1640531527,%d2
	muls.l %d0,%d1
	move.l 12(%sp),%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d1,%a0
	lea 1(%a0,%d0.l),%a0
	move.l %a0,%d0
	move.l %a0,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l #2146121005,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l 8(%sp),%d1
	eor.l %d0,%d1
	clr.w %d0
	swap %d0
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l (%sp)+,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	clr.w %d1
	swap %d1
	eor.l %d1,%d0
	rts
	.size	run_seed.isra.0, .-run_seed.isra.0
	.align	2
	.type	pm_lookup_next_run.part.0, @function
pm_lookup_next_run.part.0:
	lea (-20,%sp),%sp
	movem.l #1036,(%sp)
	move.l 24(%sp),%a2
	move.l 28(%sp),%a0
	move.l 36(%sp),%d2
	move.l 216(%a2),%d1
	addq.l #1,%d1
	move.l 212(%a2),%d0
	move.l 32(%sp),16(%sp)
	tst.l 40(%sp)
	jeq .L38
	move.l %a0,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,24(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 12(%sp),%a0
	move.b 1(%a2,%a0.l),%d1
.L33:
	mvz.b %d1,%d1
	mov3q.l #4,%d3
	cmp.l %d1,%d3
	jcc .L31
	clr.l %d1
.L31:
	tst.l %d2
	jeq .L34
	move.l %d2,28(%sp)
	movem.l (%sp),#1036
	move.l %d0,40(%sp)
	move.l 16(%sp),36(%sp)
	clr.l 32(%sp)
	move.l %d1,24(%sp)
	lea (20,%sp),%sp
	jra (pm_map.part.0)
.L38:
	clr.l -(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.b (%a2),%d1
	jra .L33
.L34:
	movem.l (%sp),#1036
	clr.l %d0
	lea (20,%sp),%sp
	rts
	.size	pm_lookup_next_run.part.0, .-pm_lookup_next_run.part.0
	.align	2
	.globl	pm_map
	.type	pm_map, @function
pm_map:
	move.l 8(%sp),%d0
	move.l 4(%sp),%d1
	move.l 12(%sp),%a0
	tst.l %d0
	jeq .L40
	move.l %a0,12(%sp)
	move.l %d0,8(%sp)
	move.l %d1,4(%sp)
	jra (pm_map.part.0)
.L40:
	rts
	.size	pm_map, .-pm_map
	.align	2
	.globl	pm_mode
	.type	pm_mode, @function
pm_mode:
	move.l 4(%sp),%a0
	tst.l 12(%sp)
	jeq .L44
	moveq #15,%d0
	cmp.l 8(%sp),%d0
	jcs .L44
	move.l 8(%sp),%d1
	mvz.b 1(%a0,%d1.l),%d0
.L45:
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jcc .L43
	clr.l %d0
.L43:
	rts
.L44:
	mvz.b (%a0),%d0
	jra .L45
	.size	pm_mode, .-pm_mode
	.align	2
	.globl	pm_reset
	.type	pm_reset, @function
pm_reset:
	move.l %a2,-(%sp)
	moveq #15,%d1
	move.l %d2,-(%sp)
	move.l 16(%sp),%d0
	move.l 12(%sp),%a0
	cmp.l %d0,%d1
	jcs .L52
	moveq #12,%d1
	muls.l %d0,%d1
	move.l #-2048144789,%d2
	muls.l %d2,%d0
	clr.w %d2
	lea (%a0,%d1.l),%a1
	clr.l 20(%a1)
	move.w %d2,28(%a0,%d1.l)
	move.l #-1640531527,%d2
	move.l 216(%a0),%d1
	muls.l %d2,%d1
	moveq #15,%d2
	move.l %d1,%a2
	lea 1(%a2,%d0.l),%a2
	move.l %a2,%d0
	move.l %a2,%d1
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	move.l #2146121005,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	lsr.l %d2,%d1
	move.l #2146121005,%d2
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l 212(%a0),%d1
	eor.l %d0,%d1
	clr.w %d0
	swap %d0
	eor.l %d0,%d1
	move.l %d1,%d0
	clr.w %d0
	swap %d0
	eor.l %d1,%d0
	muls.l %d2,%d0
	moveq #15,%d2
	move.l %d0,%d1
	lsr.l %d2,%d1
	eor.l %d1,%d0
	move.l #-2073254261,%d1
	muls.l %d1,%d0
	move.l %d0,%d1
	clr.w %d1
	swap %d1
	eor.l %d1,%d0
	move.l %d0,24(%a1)
.L52:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	rts
	.size	pm_reset, .-pm_reset
	.align	2
	.globl	pm_reset_all
	.type	pm_reset_all, @function
pm_reset_all:
	lea (-12,%sp),%sp
	move.l 16(%sp),%a1
	move.l #-1640531527,%d1
	movem.l #28,(%sp)
	move.l 216(%a1),%d0
	addq.l #1,%d0
	muls.l %d0,%d1
	move.l 212(%a1),%d2
	lea (20,%a1),%a0
	lea (212,%a1),%a1
	move.l %d0,4(%a1)
	addq.l #1,%d1
.L57:
	move.l %d1,%d0
	move.l #2146121005,%d4
	clr.w %d0
	swap %d0
	clr.l (%a0)
	clr.w %d3
	lea (12,%a0),%a0
	eor.l %d1,%d0
	add.l #-2048144789,%d1
	move.w %d3,-4(%a0)
	muls.l %d4,%d0
	moveq #15,%d4
	move.l %d0,%d3
	lsr.l %d4,%d3
	move.l #2146121005,%d4
	eor.l %d3,%d0
	move.l #-2073254261,%d3
	muls.l %d3,%d0
	move.l %d2,%d3
	eor.l %d0,%d3
	clr.w %d0
	swap %d0
	eor.l %d0,%d3
	move.l %d3,%d0
	clr.w %d0
	swap %d0
	eor.l %d3,%d0
	muls.l %d4,%d0
	moveq #15,%d4
	move.l %d0,%d3
	lsr.l %d4,%d3
	eor.l %d3,%d0
	move.l #-2073254261,%d3
	muls.l %d3,%d0
	move.l %d0,%d3
	clr.w %d3
	swap %d3
	eor.l %d3,%d0
	move.l %d0,-8(%a0)
	cmp.l %a0,%a1
	jne .L57
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	pm_reset_all, .-pm_reset_all
	.align	2
	.globl	pm_init
	.type	pm_init, @function
pm_init:
	move.l 8(%sp),%d1
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #220,%d0
.L62:
	clr.b (%a0)+
	cmp.l %a0,%d0
	jne .L62
	tst.l %d1
	jne .L63
	move.l #1831565813,%d1
.L63:
	move.l %d1,212(%a1)
	move.l %a1,4(%sp)
	jra pm_reset_all
	.size	pm_init, .-pm_init
	.align	2
	.globl	pm_lookup_next_run
	.type	pm_lookup_next_run, @function
pm_lookup_next_run:
	lea (-16,%sp),%sp
	moveq #15,%d0
	move.l %d2,-(%sp)
	move.l 28(%sp),%d1
	move.l 24(%sp),%a0
	move.l 32(%sp),16(%sp)
	move.l 36(%sp),12(%sp)
	cmp.l %d1,%d0
	jcs .L74
	move.l 216(%a0),%a1
	addq.l #1,%a1
	move.l 212(%a0),%d0
	tst.l 40(%sp)
	jeq .L79
	move.l %d1,-(%sp)
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,20(%sp)
	move.l %a0,16(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 8(%sp),%d1
	move.l 4(%sp),%a0
	move.b 1(%a0,%d1.l),%d1
.L73:
	mvz.b %d1,%d1
	mov3q.l #4,%d2
	cmp.l %d1,%d2
	jcc .L72
	clr.l %d1
.L72:
	tst.l 12(%sp)
	jeq .L75
	move.l %d0,40(%sp)
	move.l 16(%sp),36(%sp)
	clr.l 32(%sp)
	move.l 12(%sp),28(%sp)
	move.l %d1,24(%sp)
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	jra (pm_map.part.0)
.L79:
	clr.l -(%sp)
	move.l %a1,-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,16(%sp)
	jsr (run_seed.isra.0)
	lea (12,%sp),%sp
	move.l 4(%sp),%a0
	move.b (%a0),%d1
	jra .L73
.L74:
	move.l 16(%sp),%d0
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	rts
.L75:
	move.l (%sp)+,%d2
	clr.l %d0
	lea (16,%sp),%sp
	rts
	.size	pm_lookup_next_run, .-pm_lookup_next_run
	.align	2
	.globl	pm_advance
	.type	pm_advance, @function
pm_advance:
	lea (-12,%sp),%sp
	move.l 20(%sp),%d0
	movem.l #28,(%sp)
	move.l 24(%sp),%d1
	moveq #15,%d2
	cmp.l %d0,%d2
	jcs .L80
	tst.l 28(%sp)
	jeq .L83
	cmp.l 28(%sp),%d1
	jcs .L83
	move.l 28(%sp),%d4
	move.l %d1,%d3
	remu.l %d4,%d2:%d3
	move.l %d2,%d1
.L83:
	moveq #12,%d3
	muls.l %d3,%d0
	move.l 16(%sp),%a0
	add.l %d0,%a0
	tst.b 29(%a0)
	jeq .L89
	mvz.b 28(%a0),%d2
	cmp.l %d2,%d1
	jeq .L80
	jcc .L86
	addq.l #1,20(%a0)
.L86:
	move.l 16(%sp),%a0
	move.b %d1,28(%a0,%d0.l)
.L80:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L89:
	moveq #1,%d4
	move.b %d4,29(%a0)
	move.l 16(%sp),%a0
	move.b %d1,28(%a0,%d0.l)
	jra .L80
	.size	pm_advance, .-pm_advance
	.align	2
	.globl	pm_lookup
	.type	pm_lookup, @function
pm_lookup:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 20(%sp),%d1
	move.l 16(%sp),%a1
	move.l 28(%sp),%a0
	move.l 24(%sp),8(%sp)
	cmp.l %d1,%d2
	jcs .L95
	tst.l 32(%sp)
	jeq .L92
	moveq #12,%d2
	muls.l %d1,%d2
	move.b 1(%a1,%d1.l),%d0
	move.l 24(%a1,%d2.l),%d2
	move.l %d2,4(%sp)
.L93:
	mvz.b %d0,%d0
	mov3q.l #4,%d2
	cmp.l %d0,%d2
	jcc .L94
	clr.l %d0
.L94:
	tst.l %a0
	jeq .L96
	moveq #12,%d2
	muls.l %d2,%d1
	move.l 4(%sp),32(%sp)
	move.l 8(%sp),28(%sp)
	lea 20(%a1,%d1.l),%a1
	move.l (%a1),24(%sp)
	move.l %a0,20(%sp)
	move.l %d0,16(%sp)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra (pm_map.part.0)
.L92:
	move.l 24(%a1),%d2
	move.b (%a1),%d0
	move.l %d2,4(%sp)
	jra .L93
.L95:
	move.l 8(%sp),%d0
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L96:
	move.l (%sp)+,%d2
	clr.l %d0
	addq.l #8,%sp
	rts
	.size	pm_lookup, .-pm_lookup
	.align	2
	.globl	pm_ui_step
	.type	pm_ui_step, @function
pm_ui_step:
	move.l %a2,-(%sp)
	move.l 16(%sp),%a0
	tst.l 20(%sp)
	jeq .L100
	moveq #15,%d0
	cmp.l 12(%sp),%d0
	jcs .L100
	move.l 12(%sp),%d0
	move.l 8(%sp),%a2
	move.b 1(%a2,%d0.l),%d1
	lea 1(%a2,%d0.l),%a1
	mov3q.l #4,%d0
	mvz.b %d1,%d1
	cmp.l %d1,%d0
	jcc .L102
.L119:
	tst.l %a0
	jlt .L107
	clr.l %d0
.L103:
	tst.l %a0
	sne %d1
	mvs.b %d1,%d1
	sub.l %d1,%d0
.L106:
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jlt .L118
	move.b %d0,%d1
.L104:
	move.b %d1,(%a1)
	move.l (%sp)+,%a2
	rts
.L100:
	move.l 8(%sp),%a1
	mov3q.l #4,%d0
	move.b (%a1),%d1
	mvz.b %d1,%d1
	cmp.l %d1,%d0
	jcs .L119
.L102:
	move.l %d1,%d0
	tst.l %a0
	jge .L103
	subq.l #1,%d0
	tst.l %d1
	jne .L106
.L107:
	clr.b %d1
	clr.l %d0
	move.b %d1,(%a1)
	move.l (%sp)+,%a2
	rts
.L118:
	mov3q.l #4,%d0
	move.b %d0,%d1
	jra .L104
	.size	pm_ui_step, .-pm_ui_step
	.section	.rodata.str1.1,"aMS",@progbits,1
.LC0:
	.string	"NORMAL"
	.text
	.align	2
	.globl	pm_ui_label
	.type	pm_ui_label, @function
pm_ui_label:
	move.l %a2,-(%sp)
	move.l 20(%sp),%a2
	tst.l 16(%sp)
	jeq .L121
	moveq #15,%d0
	cmp.l 12(%sp),%d0
	jcs .L121
	mov3q.l #7,%d1
	cmp.l 12(%sp),%d1
	jcs .L122
	moveq #84,%d0
	move.l 12(%sp),%d1
	add.l #49,%d1
	move.b %d1,1(%a2)
	move.l 8(%sp),%a1
	mov3q.l #3,%a0
	move.l 12(%sp),%d1
	move.b %d0,(%a2)
	moveq #32,%d0
	move.b %d0,2(%a2)
	mvz.b 1(%a1,%d1.l),%d0
.L124:
	mov3q.l #4,%d1
	cmp.l %d0,%d1
	jcs .L128
.L138:
	lea NAMES,%a1
	move.l (%a1,%d0.l*4),%a1
	move.b (%a1),%d1
	jeq .L126
	add.l %a2,%a0
.L127:
	move.b %d1,(%a0)
	move.l %a0,%d0
	addq.l #1,%a1
	addq.l #1,%a0
	move.b (%a1),%d1
	jne .L127
	mov3q.l #1,%a0
	sub.l %a2,%a0
	add.l %d0,%a0
.L126:
	clr.b %d0
	move.b %d0,(%a2,%a0.l)
	move.l %a2,%d0
	move.l (%sp)+,%a2
	rts
.L121:
	move.l 8(%sp),%a1
	mov3q.l #4,%a0
	move.l #1095519264,(%a2)
	mov3q.l #4,%d1
	mvz.b (%a1),%d0
	cmp.l %d0,%d1
	jcc .L138
.L128:
	moveq #78,%d1
	lea .LC0,%a1
	add.l %a2,%a0
	jra .L127
.L122:
	moveq #77,%d0
	mov3q.l #7,%d1
	and.l 12(%sp),%d1
	move.l 8(%sp),%a1
	mov3q.l #3,%a0
	move.b %d0,(%a2)
	moveq #32,%d0
	add.l #49,%d1
	move.b %d1,1(%a2)
	move.l 12(%sp),%d1
	move.b %d0,2(%a2)
	mvz.b 1(%a1,%d1.l),%d0
	jra .L124
	.size	pm_ui_label, .-pm_ui_label
	.align	2
	.globl	pm_per_track
	.type	pm_per_track, @function
pm_per_track:
	move.l %d2,-(%sp)
	move.l #635712,%d2
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l (%sp)+,%d2
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	tst.b (%a0,%d0.l)
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	rts
	.size	pm_per_track, .-pm_per_track
	.align	2
	.globl	pm_track_length
	.type	pm_track_length, @function
pm_track_length:
	lea (-16,%sp),%sp
	movem.l #28,(%sp)
	move.l #635712,%d2
	move.l #36437,%a1
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jeq .L157
	move.l 20(%sp),%d0
	mov3q.l #7,%d4
	cmp.l 20(%sp),%d4
	jcs .L144
	mvz.w #2330,%d1
	muls.l %d1,%d0
	moveq #81,%d1
	lea (%a0,%d0.l),%a1
	move.b 80(%a1),%d0
.L145:
	move.b (%a1,%d1.l),%d1
	mvz.b %d0,%d0
	moveq #63,%d3
	move.b %d1,12(%sp)
	move.l %d0,%d1
	subq.l #1,%d1
	cmp.l %d1,%d3
	jcc .L146
	moveq #16,%d0
.L146:
	mvz.w #36432,%d1
	move.b (%a0,%d1.l),%d1
	move.w %d1,%a1
	mvz.w #36433,%d1
	mvz.b (%a0,%d1.l),%d1
	move.l %a1,%d4
	lsl.l #8,%d4
	or.l %d4,%d1
	tst.w %d1
	jle .L141
	move.l #36436,%a1
	mov3q.l #6,%d4
	mvz.b 12(%sp),%d2
	mvz.b (%a0,%a1.l),%d3
	move.l %d2,12(%sp)
	cmp.l %d3,%d4
	jcs .L152
	lea (ticks.0),%a1
	mvz.b (%a1,%d3.l),%d2
	mov3q.l #6,%d3
	move.l %d2,%a0
	move.w %a0,%d2
	mulu.w %d2,%d1
	cmp.l 12(%sp),%d3
	jcs .L153
.L158:
	move.l 12(%sp),%d4
	lea (ticks.0),%a0
	mvz.b (%a0,%d4.l),%d4
	move.l %d4,%a0
.L149:
	lea -1(%a0,%d1.l),%a1
	move.l %a0,%d3
	move.l %a1,%d2
	divu.l %d3,%d2
	cmp.l %d0,%d2
	jcc .L141
	cmp.l %a1,%a0
	jhi .L154
	move.l %d2,%d0
.L141:
	movem.l (%sp),#28
	lea (16,%sp),%sp
	rts
.L144:
	mvz.w #2224,%d2
	moveq #41,%d1
	muls.l %d2,%d0
	move.l %d0,%a1
	lea (848,%a1),%a1
	add.l %a0,%a1
	move.b 40(%a1),%d0
	jra .L145
.L157:
	mvz.w #36435,%d0
	moveq #63,%d3
	mvz.b (%a0,%d0.l),%d0
	move.l %d0,%d1
	subq.l #1,%d1
	cmp.l %d1,%d3
	jcc .L141
	movem.l (%sp),#28
	moveq #16,%d0
	lea (16,%sp),%sp
	rts
.L152:
	mov3q.l #6,%a0
	move.w %a0,%d2
	mov3q.l #6,%d3
	mulu.w %d2,%d1
	cmp.l 12(%sp),%d3
	jcc .L158
.L153:
	mov3q.l #6,%a0
	jra .L149
.L154:
	movem.l (%sp),#28
	mov3q.l #1,%d0
	lea (16,%sp),%sp
	rts
	.size	pm_track_length, .-pm_track_length
	.align	2
	.globl	pm_seq_step
	.type	pm_seq_step, @function
pm_seq_step:
	lea (-16,%sp),%sp
	movem.l #28,(%sp)
	tst.b pm_ready.l
	jeq .L190
.L160:
	move.l -2147457608,%d0
	mov3q.l #1,%d4
	move.b -2147457603,%d3
	move.b -2147457602,%d1
	cmp.l %d0,%d4
	seq %d2
	move.b %d1,15(%sp)
	neg.l %d2
	tst.l pm_restart
	jne .L163
	cmp.l %d0,%d4
	jeq .L191
.L164:
	mvz.b %d3,%d0
	mvz.b pm_last_bank,%d1
	cmp.l %d0,%d1
	jeq .L192
.L163:
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
.L165:
	move.l 20(%sp),-(%sp)
	lea (19,%sp),%a0
	move.b %d2,pm_last_transport
	move.b %d3,pm_last_bank
	move.b (%a0),pm_last_pattern
	jsr pm_track_length
	addq.l #4,%sp
	moveq #15,%d1
	cmp.l 20(%sp),%d1
	jcs .L193
	tst.l %d0
	jeq .L168
	cmp.l 24(%sp),%d0
	jhi .L168
	move.l 24(%sp),%d2
	moveq #12,%d4
	move.l 20(%sp),%d3
	lea pm_state,%a1
	remu.l %d0,%d1:%d2
	muls.l %d4,%d3
	lea (%a1,%d3.l),%a0
	tst.b 29(%a0)
	jne .L171
.L194:
	moveq #1,%d2
	move.b %d2,29(%a0)
.L172:
	move.b %d1,28(%a1,%d3.l)
.L186:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	move.l #635712,%d4
	mulu.w #36568,%d2
	mvz.b %d1,%d1
	muls.l %d4,%d1
	move.l %d1,%a0
	add.l %d2,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	move.b (%a0,%d1.l),%d1
	jeq .L175
	move.l 20(%sp),%d2
	move.l 24(%a1,%d3.l),%a0
	move.b 1(%a1,%d2.l),%d1
.L176:
	mvz.b %d1,%d1
	mov3q.l #4,%d4
	cmp.l %d1,%d4
	jcc .L177
	clr.l %d1
.L177:
	tst.l %d0
	jeq .L159
	move.l %a0,-(%sp)
	move.l 28(%sp),-(%sp)
	move.l 20(%a1,%d3.l),-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
.L159:
	movem.l (%sp),#28
	lea (16,%sp),%sp
	rts
.L168:
	move.l 20(%sp),%d3
	moveq #12,%d4
	lea pm_state,%a1
	move.l 24(%sp),%d1
	muls.l %d4,%d3
	lea (%a1,%d3.l),%a0
	tst.b 29(%a0)
	jeq .L194
.L171:
	mvz.b 28(%a0),%d2
	cmp.l %d2,%d1
	jeq .L186
	jcc .L172
	move.b %d1,28(%a1,%d3.l)
	addq.l #1,20(%a0)
	jra .L186
.L190:
	move.l 1175473392,%d0
	lea pm_state,%a1
	move.l %a1,%a0
.L161:
	clr.b (%a0)+
	cmp.l #pm_state+220,%a0
	jne .L161
	tst.l %d0
	jeq .L195
	move.l %a1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L160
.L191:
	tst.b pm_last_transport.l
	jne .L164
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
	jra .L165
.L193:
	move.b -2147457603,%d2
	mvz.b -2147457602,%d1
	move.l #635712,%d3
	move.l 24(%sp),%d0
	mulu.w #36568,%d1
	mvz.b %d2,%d2
	move.l %d1,%a0
	mvz.w #36437,%d1
	muls.l %d3,%d2
	add.l %d2,%a0
	add.l #1074668000,%a0
	move.b (%a0,%d1.l),%d1
	movem.l (%sp),#28
	lea (16,%sp),%sp
	rts
.L175:
	move.b (%a1),%d1
	move.l pm_state+24,%a0
	jra .L176
.L192:
	mvz.b 15(%sp),%d0
	mvz.b pm_last_pattern,%d1
	cmp.l %d0,%d1
	jeq .L165
	pea pm_state
	clr.l pm_restart
	jsr pm_reset_all
	addq.l #4,%sp
	jra .L165
.L195:
	move.l #1831565813,%d0
	move.l %a1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L160
	.size	pm_seq_step, .-pm_seq_step
	.align	2
	.globl	pm_seq_peek
	.type	pm_seq_peek, @function
pm_seq_peek:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	tst.b pm_ready.l
	jeq .L214
.L197:
	move.l 12(%sp),-(%sp)
	jsr pm_track_length
	addq.l #4,%sp
	mov3q.l #1,%d1
	cmp.l -2147457608.l,%d1
	jeq .L200
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	mulu.w #36568,%d2
	mvz.b %d1,%d1
	move.l %d2,%a0
	move.l #635712,%d2
	muls.l %d2,%d1
	moveq #15,%d2
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	move.b (%a0,%d1.l),%d1
	cmp.l 12(%sp),%d2
	jcs .L201
	tst.b %d1
	sne %d1
	mvs.b %d1,%d1
	neg.l %d1
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	pea pm_state
	jsr (pm_lookup_next_run.part.0)
	lea (20,%sp),%sp
.L196:
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L200:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	mulu.w #36568,%d2
	mvz.b %d1,%d1
	move.l %d2,%a0
	move.l #635712,%d2
	muls.l %d2,%d1
	moveq #15,%d2
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	move.b (%a0,%d1.l),%d1
	cmp.l 12(%sp),%d2
	jcs .L201
	tst.b %d1
	jeq .L204
	move.l 12(%sp),%d1
	moveq #12,%d2
	lea pm_state,%a1
	muls.l %d2,%d1
	move.l 12(%sp),%d2
	move.l %d1,%a0
	move.b 1(%a1,%d2.l),%d1
	move.l 24(%a1,%a0.l),%a0
	move.l %a0,4(%sp)
.L205:
	mvz.b %d1,%d1
	move.l %d1,%a0
	mov3q.l #4,%d1
	cmp.l %a0,%d1
	jcc .L206
	sub.l %a0,%a0
.L206:
	tst.l %d0
	jeq .L196
	move.l 12(%sp),%d1
	moveq #12,%d2
	move.l 4(%sp),-(%sp)
	move.l 20(%sp),-(%sp)
	muls.l %d2,%d1
	move.l 20(%a1,%d1.l),-(%sp)
	move.l %d0,-(%sp)
	move.l %a0,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L214:
	move.l 1175473392,%d0
	lea pm_state,%a1
	move.l %a1,%a0
.L198:
	clr.b (%a0)+
	cmp.l #pm_state+220,%a0
	jne .L198
	tst.l %d0
	jeq .L215
	move.l %a1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L197
.L201:
	move.l 16(%sp),%d0
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L215:
	move.l #1831565813,%d0
	move.l %a1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L197
.L204:
	move.l pm_state+24,%a0
	lea pm_state,%a1
	move.b (%a1),%d1
	move.l %a0,4(%sp)
	jra .L205
	.size	pm_seq_peek, .-pm_seq_peek
	.align	2
	.globl	pm_show
	.type	pm_show, @function
pm_show:
	subq.l #8,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	tst.b pm_ready.l
	jeq .L246
	mov3q.l #-1,%d1
	cmp.l 20(%sp),%d1
	jeq .L247
.L220:
	moveq #15,%d3
	cmp.l 20(%sp),%d3
	jcs .L223
	move.l 20(%sp),-(%sp)
	jsr pm_track_length
	addq.l #4,%sp
	mov3q.l #1,%d1
	cmp.l -2147457608.l,%d1
	jeq .L224
.L249:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d2
	move.w %d2,%d3
	move.l #635712,%d2
	mvz.b %d1,%d1
	muls.l %d2,%d1
	mulu.w #36568,%d3
	move.l %d3,%a0
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	tst.b (%a0,%d1.l)
	sne %d1
	mvs.b %d1,%d1
	neg.l %d1
	tst.l %d0
	jeq .L225
	move.l 24(%sp),%d3
	remu.l %d0,%d2:%d3
	move.l %d2,24(%sp)
.L225:
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l 32(%sp),-(%sp)
	move.l 32(%sp),-(%sp)
	pea pm_state
	jsr (pm_lookup_next_run.part.0)
	lea (20,%sp),%sp
.L216:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #8,%sp
	rts
.L224:
	move.l 20(%sp),%d3
	moveq #12,%d1
	lea pm_state,%a1
	muls.l %d1,%d3
	lea (%a1,%d3.l),%a0
	move.l 20(%a0),%d2
	move.l %d3,12(%sp)
	move.l %d2,8(%sp)
	tst.b 29(%a0)
	jeq .L228
	mvz.b 28(%a0),%d1
	cmp.l 24(%sp),%d1
	jcc .L228
	tst.l %d2
	sne %d1
	mvs.b %d1,%d1
	add.l %d1,8(%sp)
.L228:
	move.b -2147457603,%d1
	mvz.b -2147457602,%d3
	move.w %d3,%d2
	move.l #635712,%d3
	mvz.b %d1,%d1
	muls.l %d3,%d1
	mulu.w #36568,%d2
	move.l %d2,%a0
	add.l %d1,%a0
	mvz.w #36437,%d1
	add.l #1074668000,%a0
	tst.b (%a0,%d1.l)
	jeq .L229
	tst.l %d0
	jeq .L216
	move.l 24(%sp),%d1
	move.l 20(%sp),%d3
	remu.l %d0,%d2:%d1
	mvz.b 1(%a1,%d3.l),%d1
	mov3q.l #4,%d3
	move.l %d2,%a0
	move.l 12(%sp),%d2
	move.l 24(%a1,%d2.l),%a1
	cmp.l %d1,%d3
	jcs .L236
.L231:
	move.l %a1,-(%sp)
	move.l %a0,-(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
.L250:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #8,%sp
	rts
.L246:
	move.l 1175473392,%d1
	move.l #pm_state+220,%d0
	lea pm_state,%a1
	move.l %a1,%a0
.L218:
	clr.b (%a0)+
	cmp.l %d0,%a0
	jne .L218
	tst.l %d1
	jeq .L248
	move.l %a1,-(%sp)
	move.l %d1,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
.L251:
	mov3q.l #-1,%d1
	cmp.l 20(%sp),%d1
	jne .L220
.L247:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	move.l #36437,%a1
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074668000,%a0
	tst.b (%a0,%a1.l)
	jne .L223
	clr.l 20(%sp)
	move.l 20(%sp),-(%sp)
	jsr pm_track_length
	addq.l #4,%sp
	mov3q.l #1,%d1
	cmp.l -2147457608.l,%d1
	jeq .L224
	jra .L249
.L223:
	move.l 24(%sp),%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #8,%sp
	rts
.L229:
	tst.l %d0
	jeq .L216
	move.l 24(%sp),%d1
	mov3q.l #4,%d3
	remu.l %d0,%d2:%d1
	mvz.b (%a1),%d1
	move.l pm_state+24,%a1
	move.l %d2,%a0
	cmp.l %d1,%d3
	jcc .L231
.L236:
	move.l %a1,-(%sp)
	move.l %a0,-(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d0,-(%sp)
	clr.l %d1
	move.l %d1,-(%sp)
	jsr (pm_map.part.0)
	lea (20,%sp),%sp
	jra .L250
.L248:
	move.l %a1,-(%sp)
	move.l #1831565813,%d1
	move.l %d1,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L251
	.size	pm_show, .-pm_show
	.align	2
	.globl	pm_key_updown
	.type	pm_key_updown, @function
pm_key_updown:
	move.l %d2,-(%sp)
	tst.b pm_ready.l
	jeq .L274
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	move.b (%a0,%d0.l),%d1
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	tst.l 12(%sp)
	jne .L275
.L256:
	pea pm_toast
	move.l %d0,-(%sp)
	move.l 16(%sp),-(%sp)
	pea pm_state
	jsr pm_ui_label
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	rts
.L275:
	tst.b %d1
	jeq .L257
	moveq #15,%d1
	cmp.l 8(%sp),%d1
	jcs .L257
	move.l 8(%sp),%d2
	lea pm_state,%a0
	move.l 8(%sp),%a1
	add.l #pm_state+1,%a1
	move.b 1(%a0,%d2.l),%d1
	mvz.b %d1,%d2
	move.l %d2,%a0
	mov3q.l #4,%d2
	cmp.l %a0,%d2
	jcs .L276
.L259:
	tst.l 12(%sp)
	jlt .L261
	move.l %a0,%d1
	mov3q.l #4,%d2
	addq.l #1,%d1
	cmp.l %d1,%d2
	jlt .L277
	move.b %d1,(%a1)
.L279:
	pea pm_toast
	move.l %d0,-(%sp)
	move.l 16(%sp),-(%sp)
	pea pm_state
	jsr pm_ui_label
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	rts
.L274:
	move.l 1175473392,%d0
	move.l #pm_state,%d1
	move.l %d1,%a0
.L254:
	clr.b (%a0)+
	cmp.l #pm_state+220,%a0
	jne .L254
	tst.l %d0
	jeq .L278
	move.l %d1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
.L280:
	move.b -2147457603,%d0
	mvz.b -2147457602,%d1
	move.l #635712,%d2
	mulu.w #36568,%d1
	mvz.b %d0,%d0
	muls.l %d2,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	mvz.w #36437,%d0
	add.l #1074668000,%a0
	move.b (%a0,%d0.l),%d1
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	tst.l 12(%sp)
	jeq .L256
	jra .L275
.L257:
	move.b pm_state,%d1
	lea pm_state,%a1
	mvz.b %d1,%d2
	move.l %d2,%a0
	mov3q.l #4,%d2
	cmp.l %a0,%d2
	jcc .L259
.L276:
	move.l 12(%sp),%d1
	not.l %d1
	add.l %d1,%d1
	subx.l %d1,%d1
	neg.l %d1
	move.b %d1,(%a1)
	jra .L279
.L278:
	move.l #1831565813,%d0
	move.l %d1,-(%sp)
	move.l %d0,pm_state+212
	jsr pm_reset_all
	moveq #1,%d0
	addq.l #4,%sp
	move.b %d0,pm_ready
	jra .L280
.L261:
	tst.l %a0
	jeq .L264
	subq.l #1,%d1
	move.b %d1,(%a1)
	jra .L279
.L277:
	mov3q.l #4,%d1
	move.b %d1,(%a1)
	jra .L279
.L264:
	clr.b %d1
	move.b %d1,(%a1)
	jra .L279
	.size	pm_key_updown, .-pm_key_updown
	.section	.rodata
	.type	ticks.0, @object
	.size	ticks.0, 7
ticks.0:
	.base64	"AwQGCAwYMA=="
	.section	.rodata.str1.1
.LC1:
	.string	"REVERSED"
.LC2:
	.string	"PINGPONG"
.LC3:
	.string	"RANDOM"
.LC4:
	.string	"SHUFFLE"
	.section	.rodata
	.align	2
	.type	NAMES, @object
	.size	NAMES, 20
NAMES:
	.long	.LC0
	.long	.LC1
	.long	.LC2
	.long	.LC3
	.long	.LC4

| ---- hooks.s ----
| PLAY MODES -- the hand-written part of the unit: the detour stubs, the
| register-saving entries they call, and the state the C keeps in
| loader-owned DRAM. generate.py appends this to the compiled playmode.c +
| adapter.c.
|
| Sites read from the owner's original 1.40C with investigate.py (rounds 1
| and 2, 3 Oct 2026); INVESTIGATION.md section 4 has the stock listings.
| Every stub is reached by a six-byte `jmp` that the manifest plants over
| whole stock instructions, replays them, and jumps back.
        .text
        .balign 4
        .global pm_step_entry, pm_peek_entry, pm_show_entry, pm_key_entry

| pm_step_entry(track, raw) -> d0 = the step to play.
| Saves everything the C may clobber except d0, so a stub can call it in
| the middle of stock code: push raw, push track, jsr, addq #8,sp.
pm_step_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)          | raw
        move.l  20(%sp),-(%sp)          | track (shifted by the first push)
        jsr     pm_seq_step
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_peek_entry(track, raw) -> d0: the look-ahead form, no state change.
pm_peek_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)
        move.l  20(%sp),-(%sp)
        jsr     pm_seq_peek
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_show_entry(track, raw) -> d0: the step the display should show.
pm_show_entry:
        lea     -12(%sp),%sp
        movem.l %d1/%a0-%a1,(%sp)
        move.l  20(%sp),-(%sp)
        move.l  20(%sp),-(%sp)
        jsr     pm_show
        addq.l  #8,%sp
        movem.l (%sp),%d1/%a0-%a1
        lea     12(%sp),%sp
        rts

| pm_key_entry(track, delta): TRACK held + UP (-1) / DOWN (+1). Changes the
| mode and opens the stock toast with the new text. Key-handler context
| ONLY: the toast's close path reaches the kernel post 0x40000c3c, which
| hard-crashed a unit when reached from the frame path (Kyoti, Session 93).
| The duration must be > 0 (0 or less hung a unit: Kyoti, Session 50).
        .equ    NOTIFY, 0x4005a2b8      | FUN_4005a2b8(text, duration)
        .equ    REBUILD, 0x4009da20     | the working-set rebuild an edit calls; -1 = all tracks
        .equ    TOAST_TIME, 0x3c        | 1 s at the 60 Hz UI tick
pm_key_entry:
        lea     -16(%sp),%sp
        movem.l %d0-%d1/%a0-%a1,(%sp)
        move.l  24(%sp),-(%sp)          | delta
        move.l  24(%sp),-(%sp)          | track
        jsr     pm_key_updown           | fills pm_toast
        addq.l  #8,%sp
        pea     TOAST_TIME
        pea     pm_toast
        jsr     NOTIFY
        addq.l  #8,%sp
        pea     0xffffffff              | re-prepare every track's step in the
        jsr     REBUILD                 | new mode, as stock does after an edit
        addq.l  #4,%sp
        movem.l (%sp),%d0-%d1/%a0-%a1
        lea     16(%sp),%sp
        rts

| ---- the detour stubs ------------------------------------------------------
        .global pm_audio_step, pm_midi_step, pm_audio_rebuild, pm_midi_rebuild
        .global pm_arrow_key, pm_track_key, pm_step_getter
        .global pm_start_play, pm_start_ext1, pm_start_ext2, pm_start_ext3

| 0x400a2d6a, the tick's audio pass, just before 0x4009d1e8(track, bank,
| pattern, step, n): stock loads step = 0x800064d0[track] (track in d5).
| Displaced: lea 0x800064d0,%a0 (6). The next instruction, mvzb
| (0,%a0,%d5.l),%d0, is done here and skipped on the way back.
pm_audio_step:
        lea     0x800064d0,%a0
        mvz.b   %a0@(0,%d5:l),%d0         | MIT syntax, as objdump prints it
        move.l  %d0,-(%sp)              | raw step
        move.l  %d5,-(%sp)              | track 0..7
        jsr     pm_step_entry           | d0 := the step to play; d1/a0/a1 kept
        addq.l  #8,%sp
        jmp     0x400a2d74              | movel %d0,%sp@- (the step argument)

| 0x400a39b6, the tick's MIDI pass, before 0x4009cf4c(track, bank, pattern,
| step, n): step = 0x800064d0[8 + track] via the walking pointer at
| 100(%sp); MIDI track in d7. Displaced (8, the manifest pads one nop):
| moveal %sp@(100),%a0 ; mvzb %a0@(8),%d0. A jmp leaves sp as stock had it.
pm_midi_step:
        movea.l 100(%sp),%a0
        mvz.b   8(%a0),%d0
        move.l  %d0,-(%sp)
        move.l  %d7,%d1
        addq.l  #8,%d1                  | the engine's MIDI tracks are 8..15
        move.l  %d1,-(%sp)
        jsr     pm_step_entry
        addq.l  #8,%sp
        jmp     0x400a39be              | movel %d0,%sp@-

| 0x4009dc86 / 0x4009e3dc, the working-set rebuild 0x4009da20 (after an
| edit): stock computes the current step in d2 and calls the step handler
| with n = -1. Track in d6 (0..7 audio; 8..15 on the MIDI branch, which
| 0x4009dc78 takes when d6 > 7). Displaced: pea 0xffffffff ; movel %d2,
| %sp@- (6). The look-ahead form: no engine state changes.
pm_audio_rebuild:
        pea     0xffffffff
        move.l  %d2,-(%sp)
        move.l  %d6,-(%sp)
        jsr     pm_peek_entry
        addq.l  #8,%sp
        move.l  %d0,-(%sp)
        jmp     0x4009dc8c

pm_midi_rebuild:
        pea     0xffffffff
        move.l  %d2,-(%sp)
        move.l  %d6,-(%sp)
        jsr     pm_peek_entry
        addq.l  #8,%sp
        move.l  %d0,-(%sp)
        jmp     0x4009e3e2

| 0x4009b2b0, stock step(track): track < 0 returns the master step
| (0x800065b4); otherwise it branches to 0x4009b2be for the track's own
| step. Its 11 callers are UI code: the trig LEDs, live recording, lock
| editing (track = the current track, MIDI tracks as 8 + t; -1 for the
| master). Both answers are mapped like the step that plays (the master
| only under NORMAL scale mode). Displaced: movel %sp@(4),%d0 ;
| bges 0x4009b2be (6).
pm_step_getter:
        move.l  4(%sp),%d0
        bge.s   .Lgetter_track
        mvz.w   0x800065b4,%d0          | stock: the master step
        move.l  %d0,-(%sp)              | raw
        pea     0xffffffff              | "track" -1: the master
        jsr     pm_show_entry           | mapped under NORMAL scale mode
        addq.l  #8,%sp
        rts
.Lgetter_track:
        move.l  %d0,-(%sp)              | call the stock per-track branch as
        jsr     0x4009b2be              | stock enters it: d0 = track, arg at 4(sp)
        addq.l  #4,%sp
        move.l  %d0,-(%sp)              | raw step
        move.l  8(%sp),-(%sp)           | track (the caller's argument)
        jsr     pm_show_entry
        addq.l  #8,%sp
        rts

| The four places that set the transport playing (0x800065b8 := 1), each
| followed by the same `lea 0x4610757c,%a0` (6), displaced here: PLAY
| 0x4009c3da (EUCLID's PLAY stub returns to this very address, so the two
| compose), and 0x400a2210 / 0x400a24d6 / 0x400a27e8 in the tick (external
| start / continue). Raise pm_restart. Only a0 is used (the displaced lea
| loads it next); data registers stay as stock left them (d0/d1/d5 hold the
| 1 just stored), and the next stock instruction sets the condition codes.
pm_start_play:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x4009c3e0
pm_start_ext1:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a2216
pm_start_ext2:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a24dc
pm_start_ext3:
        lea     pm_restart,%a0
        move.l  #1,(%a0)                | no data register touched
        lea     0x4610757c,%a0
        jmp     0x400a27ee

| 0x40040250, the TRACK key handler (codes 0x10..0x17), handler(code,
| event): event 1 = press, 0 = release (as the REC handler 0x40048774 reads
| it), other values (hold, repeat) leave the state alone. Stock has no plain
| "TRACK held" byte: 0x400c0aac is its double-tap memory and survives the
| release. So the held key is kept here, as track + 1 (0 = none, which is
| also what the zeroed DRAM starts with). Displaced: movel %d2,%sp@- ;
| movel %sp@(8),%d1 (6). d0 is free: stock loads it next.
pm_track_key:
        move.l  4(%sp),%d1
        subi.l  #0x0f,%d1               | code 0x10..0x17 -> 1..8
        beq.s   .Ltrack_stock
        moveq   #8,%d0
        cmp.l   %d0,%d1
        bhi.s   .Ltrack_stock           | unsigned: not a TRACK key
        move.l  8(%sp),%d0
        cmpi.l  #1,%d0
        bne.s   .Ltrack_other
        move.l  %d1,pm_held_track       | press
        bra.s   .Ltrack_stock
.Ltrack_other:
        tst.l   %d0
        bne.s   .Ltrack_stock           | hold / repeat: keep
        cmp.l   pm_held_track,%d1       | release of the held key
        bne.s   .Ltrack_stock
        clr.l   pm_held_track
.Ltrack_stock:
        move.l  %d2,-(%sp)              | displaced
        move.l  8(%sp),%d1              | displaced
        jmp     0x40040256

| 0x400491a0, the UP / DOWN handler (key codes 0x33 / 0x20), handler(code,
| event). Stock acts on the main screen only inside the arranger or one
| mode check; otherwise it returns. With a TRACK key held (pm_held_track) a
| press changes the play mode and is consumed. MIDI mode (0x80000012 != 0)
| addresses M1..M8.
| ASSUMED, to confirm on the unit: 0x33 is UP (towards NORMAL). If the
| toast walks the wrong way, change KEY_UP to 0x20.
        .equ    KEY_UP, 0x33
        .equ    MIDI_MODE, 0x80000012
pm_arrow_key:
        move.l  8(%sp),%d0              | ColdFire cmpi takes a data register only
        cmpi.l  #1,%d0                  | a press?
        bne.s   .Larrow_stock
        move.l  pm_held_track,%d0       | 1..8, 0 = none
        beq.s   .Larrow_stock
        subq.l  #1,%d0
        tst.l   MIDI_MODE
        beq.s   .Larrow_audio
        addq.l  #8,%d0
.Larrow_audio:
        moveq   #1,%d1                  | DOWN: towards SHUFFLE
        move.l  4(%sp),%a0
        cmpa.l  #KEY_UP,%a0
        bne.s   .Larrow_delta
        moveq   #-1,%d1                 | UP: towards NORMAL
.Larrow_delta:
        move.l  %d1,-(%sp)
        move.l  %d0,-(%sp)
        jsr     pm_key_entry            | change the mode, open the toast
        addq.l  #8,%sp
        rts                             | consumed: back to the key dispatcher
.Larrow_stock:
        move.l  %d2,-(%sp)              | displaced
        movea.l 8(%sp),%a0              | displaced
        jmp     0x400491a6

| Explicitly initialised, loader-owned DRAM (as EUCLID's state), not the
| 0x80006a40 scratch block, which the live DSP path overwrites. The C's
| _Static_asserts pin the sizes.
        .balign 4
        .global pm_state, pm_ready, pm_last_transport, pm_last_bank
        .global pm_last_pattern, pm_toast, pm_held_track, pm_restart
pm_state:
        .zero   224
pm_ready:
        .byte   0
pm_last_transport:
        .byte   0
pm_last_bank:
        .byte   0
pm_last_pattern:
        .byte   0
pm_toast:
        .zero   16
pm_held_track:
        .long   0                       | the held TRACK key + 1, 0 = none
pm_restart:
        .long   0                       | 1 = a transport start since the last step
